### ISSUE TITLE
Add a CONTRIBUTING.md template

### ISSUE THREAD

**Issue by tomzx** [eXolnet/php-composer-template#1]
When a template has been written, reuse it in our other projects.
- [ ] eXolnet/grunt-laravel-build-scripts#3
- [ ] eXolnet/laravel-cache-bursing#2
- [ ] eXolnet/laravel-sqlite-database-migrator#2
- [ ] eXolnet/laravel-closure-tree#2
